### ISSUE TITLE
V4.1.7 - repeated false alarms with recent update - garmin 735xt

### ISSUE THREAD

**Issue by robertcaswell** [OpenSeizureDetector/Android_Pebble_SD#104]
Hi, 

Fantastic app - however since a recent automatic update to 4.1.7, multiple false alarms have been occurring despite no epileptic activity. 
Have tried to increase:
Alarm Threshold 100 -> 500
Alarm Ratio Threshold 50 -> 70 -> 90.
Disabling AI Neural Network Algorithm.
Enabling Simple Heart Rate lowerHR = 40, highHR=150.

Should I revert to previous versions because of the older watch?

**Comment by jones139** [comment]
Thanks for reporting this - it should not have made any real difference to false alarm rate, especially if you disable the CNN algorithm.   
Are you signed in to the Data Sharing system?   I could have a look at some of your false alarms and see what is causing it.
I'd rather see if we can find the problem before you revert to the previous release if possible.   Note that Alarm Ratio Threshold of 90 is too high - if you take it much above 60 the seizure detection reliability starts to drop off noticeably....but there again, I do not know what is causing the false alarms yet.
Thanks
Graham.

**Comment by jones139** [comment]
This is going to need some analysis of the user's data, so will fix in V4.1.9 as V4.1.8 is ready now.

**Comment by jones139** [comment]
@robertcaswell sorry if I missed a reply - do you have some false alarm events on the data sharing system that you'd like me to look at to see what the issue is?

**Comment by jones139** [comment]
Is this still a problem?  You can see the false alarm rate that we are achieving here:  https://www.openseizuredetector.org.uk/?p=2052

**Comment by jones139** [comment]
No response, so closing - will re-open if it crops up again.
