### ISSUE TITLE
V4.2.x - PineTime Time/Date not Synchronised to phone

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#148]
If the pinetime watch battery dies, the time is likely to re-set.   It is not synchronised to the phone via OpenSeizureDetector - you need to connect using GadgetBridge to get it to synchronise.
Having OpenSeizureDetector synchronise the time when the watch connects would be useful.

**Comment by AroonPro** [comment]
Is it possible to fetch ntp to PineTime?

Op do 7 mrt 2024 21:00 schreef Graham Jones ***@***.***>:

**Comment by jones139** [comment]
> Is it possible to fetch ntp to PineTime? 

No, there is no internet connection on the watch - there is a BLE characteristic that you have to write data to to set the time.

**Comment by jones139** [comment]
I found a ready to use library that provides the Current Time Service (https://github.com/RideBeeline/android-bluetooth-current-time-service) so have incorporated that into BLE data source.

**Comment by jones139** [comment]
Pull Request #165 fixes this, which is now merged into V4.2.x development branch.
