### ISSUE TITLE
v4.2.x Enabling Puls Alarm using PineTime causes Alarm to trigger all the time

### ISSUE THREAD

**Issue by seaside1** [OpenSeizureDetector/Android_Pebble_SD#150]
Steps to reproduce:

1) Launch app with a pine time
2) Under Settings-> Seizure Detector under section "Simple Heart Rate Alarm Setting"  enable Puls Alarm (Heart rate measurement frozen warning not enabled, Alarm vi zeropuls not enabled) (Using default values of min puls: 40 max puls 150)
3) Now going back to the app or retarting it by "Force stop" the alarm will trigger no matter what thresholds are set under puls min / max

Another question, Why are there two " Puls Alarms" under settings? One under Algorithm settings and another one under Simple Heart Rate Alarm Setting? Maybe the one under algorithm should be removed?

**Comment by jones139** [comment]
Thanks- I'll have a look this evening- I thought it was working OK!

**Comment by jones139** [comment]
Well, I might have found the issue, and it is in the PineTime firmware - although we switch on the heart rate monitor when the pinetime boots, the indicated heart rate was zero.   If I go into the heart rate app (swipe up from main screen and press the heart icon), and switch the heart rate monitor off and then on again, it starts registering the correct heart rate.
You can see the heart rate history in V4.2.x by swiping the graph at the bottom of the main screen to the right.
I'll try re-booting the pinetime a few times and see if I can find out why the heart rate value does not start automatically.

For your other question, the reason the 'Enable Simple Heart Rate alarm' checkbox appears twice is to make it easier to just scan down and enable and disable algorithms, as they are all at the top - the detail for each algorithm is further down and we put the 'Enable' checkbox with the detailed settings too.

**Comment by jones139** [comment]
As this is really a bug on the Pinetime Firmware, I have created a new issue (https://github.com/OpenSeizureDetector/PineTimeSD/issues/13) and will close this one.

**Comment by jones139** [comment]
For some reason github is showing this as completed trying to close it again with a different closure tag.
