### ISSUE TITLE
Phone Data Source shows watch battery level as zero

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#55]
We should use the phone battery level when using phone data source.

**Comment by AroonPro** [comment]
The last push into AroonPro/PebbleSd/v4.2.x_Upstream has the power level linked in from SdServer

**Comment by jones139** [comment]
Excellent, thank you - will close this once we merge it into the main repository.

**Comment by AroonPro** [comment]
Today I will double test. I have issues with SdDataSource.java.

Op zo 25 jun. 2023 21:00 schreef Graham Jones ***@***.***>:

**Comment by jones139** [comment]
I think I have it now in V4.2.x, thanks!
